defmodule Academy.SkillLevelView do
  @moduledoc ~S"""
  Module used to render skill levels related pages (e.g. My skills page).
  """

  use Academy.Web, :view

  use Phoenix.HTML

  @doc ~S"""
  Get the level of a given skill for the given user
  """
  def get_skill_level(user, skill) do
    case Academy.SkillLevelController.find_skill_level(user, skill.id) do
      nil -> 0
      skill_level -> skill_level.level
    end
  end

  @doc ~S"""
  Generate a HTML input asking for a given skill of the given user
  """
  def rating_input(user, skill) do
    {:safe,
      "<input id=\"skill_#{skill.id}\" max=\"5\" min=\"0\" name=\"skill_levels[skill_#{skill.id}]\" type=\"number\" value=\"#{get_skill_level(user, skill)}\">"}
  end

  @doc ~S"""
  Generate a HTML label to be associated with an input generated by `rating_input/2`
  """
  def rating_label(skill) do
    content_tag :label, skill.name, for: "skill_#{skill.id}"
  end

end
