defmodule Academy.SkillLevelView do
  @moduledoc ~S"""
  Module used to render skill levels related pages (e.g. My skills page).
  """

  use Academy.Web, :view

  use Phoenix.HTML

  alias Academy.SkillCategoryView

  @doc ~S"""
  Get the level of a given skill for the given user
  """
  def get_skill_level(user, skill) do
    case Academy.SkillLevelController.find_skill_level(user, skill.id) do
      nil -> 0
      skill_level -> skill_level.level
    end
  end

  @doc ~S"""
  Generate a HTML input asking for a given skill of the given user
  """
  def rating_input(f, user, skill) do
    number_input f,
      String.to_atom("skill_#{skill.id}"),
      min: 0,
      max: 5,
      value: get_skill_level(user, skill)
  end

  @doc ~S"""
  Generate a HTML label to be associated with an input generated by `rating_input/2`
  """
  def rating_label(skill) do
    content_tag :label, skill.name, for: "skill_levels_skill_#{skill.id}"
  end

end
